### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by flavioprattico** [GIPAT-Polyshaper/PolyShaper_inkscape#3]
Dal momento che si può agevolmente modificare la dimensione della pagina con le dimensioni di lavoro forse dovremmo dare un nuovo significato ai parametri dell'area di lavoro ossia un warning message qualora le dimensioni del disegno superino quelle dell'area di lavoro.

**Comment by Tomassino** [comment]
Changes:
- Specified dimensions are those of the piece to cut. Add a warning if drawing goes outside the piece but generate G-Code nonetheless. The working area that is drawn by the plugin uses these dimensions
- Add a combo-box to select the machine (P400, P1000, P1000plus, Custom or Unknown). Check that the piece to cut is smaller than the maximum dimension of the machine and generate an error otherwise (do not generate G-Code). Custom allows specifying maximum dimensions in the "Advanced" pane and Unknown disables the check

**Comment by Tomassino** [comment]
Solving in branch [dimensions-warnins](/GIPAT-Polyshaper/PolyShaper_inkscape/tree/dimensions-warnings)

**Comment by Tomassino** [comment]
Fixed #10
